settings:
  jira_project_key: "DOCPR"
  epic_key: "DOCPR-2376"
  components:
    - Starter Pack
  labels:
    - "bug"
    - "documentation"
    - "enhancement"
    - "improvement"
    - "question"
  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected
  # Adds a comment with the JIRA ID
  add_gh_comment: true
  # Reflect changes on JIRA
  sync_description: true
  # Comments are synced from Github to JIRA
  # Nothing goes from JIRA to Github
  sync_comments: true
  label_mapping:
    "bug": Bug
    "documentation": Task
    "enhancement": Task
    "improvement": Task
    "question": Spike
